{% set name = "pomegranate" %}
{% set version = "0.12.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/jmschrei/{{ name }}/archive/v{{ version }}.tar.gz"
  sha256: "c48c8ca65b1ba6268ec747cc04d915fdd1578714f8a269663abce583a441426f"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy >=1.8.0
    - pip
    - python
    - scipy >=0.17.0
  run:
    - joblib >=0.9.0b4
    - networkx >=2.0
    - {{ pin_compatible("numpy") }}
    - python
    - pyyaml
    - scipy >=0.17.0

test:
  imports:
    - pomegranate
    - pomegranate.distributions

about:
  home: "http://pypi.python.org/pypi/pomegranate/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Pomegranate is a graphical models library for Python, implemented in Cython for speed."
  doc_url: "https://pomegranate.readthedocs.io"
  dev_url: "https://github.com/jmschrei/pomegranate"

extra:
  recipe-maintainers:
    - micknudsen
