travis:
  secure:
    BINSTAR_TOKEN: jykn85LHCuPkKV36eCieHkpWkGyF+Jr6J2PyT6JH88r5NdukJvWik+vjClFwy1o5QoTPcfH+RLHbRgfwL2Fino1RiOzJNndd7PaLQXtpVn2uY51yzV4KkSFgQZhYVhC/TQX0EQwHLLqW0OslrzVn6KRHVUCh57OWMVHxxDkv41lvZDJzjI/32TIpHq+miaRIPNorQqs71bJGB5EdPo7jYcQ73uVE437UKmKkOhAPuX+ALbhNf5g3X/3ouZL4ppCHhGjmmrxvcvalWcDDQWnEGThqL9/q5veO5u2wUZjhDpcZYCMIWa5NRwuozhWwiw2Xto34arTTEXvo/htfaq52P8zuQG/3keqrwAGNs8dCosBIHiAXxApxGk1+n1R4XSXL6/AoDPku2l3nMlUPLaQCx9V1F4Wgi6+JwBqXMfHQKVQyVP0CXzQ+g3maUjh6A8VVGMdHik9XKxcGtzTeVs7SZIW8hb8ERc+AHiP0vbjAkxYft2Bqlen+1ATTIXxXvTb5OqNnEPCI258YQxoFW4zJ8+tNKX9pjUaDLQoXGHNBnJjirKd6GF5w6zltKweLy9lBo3erIqJlWyVz+BcbEvRxf2MwfXpEbBdvhNHyXZ29u2giwHcyFntVnF/bVDUr/J/daz9a+qoCDM0F0LhZpry32LZL7qLd+PMERnPIN7tEOuw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
